# Generated by Django 3.2.5 on 2022-02-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('content', models.TextField(verbose_name='편지 내용')),
                ('card_from', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='보내는 사람')),
                ('password', models.CharField(default=None, max_length=10, verbose_name='비밀번호')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('card_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
